{{- range $app := .Values.applications }}
{{- if and $app.enabled $app.autoscaling $app.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $app.name }}-hpa
  namespace: {{ $.Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ $app.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $app.name }}
  minReplicas: {{ $app.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $app.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if $app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
